name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/campus-collective:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/campus-collective:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup cloudflared
        uses: AnimMouse/setup-cloudflared@v2

      - name: Deploy to server via Cloudflare Access SSH
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -o ProxyCommand="cloudflared access ssh --hostname ${{ secrets.SERVER_SSH_HOST }} --service-token-id ${{ secrets.CF_ACCESS_CLIENT_ID }} --service-token-secret ${{ secrets.CF_ACCESS_CLIENT_SECRET }}" \
              ${{ secrets.SERVER_SSH_USER }}@${{ secrets.SERVER_SSH_HOST }} << 'EOF'
            docker pull ghcr.io/${{ github.repository_owner }}/campus-collective:latest
            docker stop campus-collective || true
            docker rm campus-collective || true
            docker run -d --name campus-collective -p 3000:3000 ghcr.io/${{ github.repository_owner }}/campus-collective:latest
          EOF
